# Generated by Django 3.1.1 on 2021-02-04 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=100, unique=True, verbose_name='Employee COde')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('password', models.CharField(max_length=20, verbose_name='Pin')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile No')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Id')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('area', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile_area', to='Configuration.areamaster', verbose_name='Area')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile_auth_user', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile_user_type', to='Configuration.usertype', verbose_name='User Type')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': ' Customer Profiles',
            },
        ),
    ]
