# Generated by Django 3.1.1 on 2021-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='barcode_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode Info'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='barcode_pic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode Pic'),
        ),
    ]
