# Generated by Django 3.1.1 on 2021-02-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20210204_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='extn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='extn'),
        ),
    ]
