# Generated by Django 3.1.1 on 2021-04-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
    ]
