# Generated by Django 3.1.1 on 2021-04-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
    ]
