# Generated by Django 3.1.1 on 2021-02-06 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True, verbose_name='Patient ID')),
                ('patient_name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=20, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile No')),
                ('sex', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sex')),
                ('age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Age')),
                ('date_of_collection', models.DateTimeField(blank=True, null=True, verbose_name='Date Of Collection')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnois')),
                ('no_of_doses', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnois')),
                ('barcode_pic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode Pic')),
                ('barcode_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode Info')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_auth_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': ' Customer Profiles',
            },
        ),
    ]
