# Generated by Django 3.1.1 on 2021-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_auto_20210208_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
