# Generated by Django 3.1.1 on 2021-02-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_samplecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecollection',
            name='patient_id',
            field=models.CharField(max_length=100, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='splittest',
            name='patient_id',
            field=models.CharField(max_length=100, verbose_name='Patient ID'),
        ),
    ]
