# Generated by Django 3.1.1 on 2021-02-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20210209_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splittest',
            name='patient_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
