# Generated by Django 3.1.1 on 2021-02-11 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_auto_20210209_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, verbose_name='Patient ID')),
                ('rate', models.CharField(max_length=100, verbose_name='Name')),
                ('paid', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Paid')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
            ],
            options={
                'verbose_name': 'PaidAmount',
                'verbose_name_plural': ' PaidAmount',
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': ' Patient'},
        ),
    ]
