# Generated by Django 3.1.1 on 2021-02-13 05:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_auto_20210211_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='paid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
