# Generated by Django 3.1.1 on 2021-02-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0013_auto_20210218_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecollection',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnois'),
        ),
    ]
