# Generated by Django 3.1.1 on 2021-02-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_samplecollection_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecollection',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='sex',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sex'),
        ),
    ]
