# Generated by Django 3.1.1 on 2021-02-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20210209_0653'),
        ('Patient', '0016_auto_20210219_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscusionOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, verbose_name='Patient ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile No')),
                ('sex', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sex')),
                ('age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Age')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='Location')),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnois')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InscusionOut_user', to='Customer.customerprofile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Inscusion Out',
                'verbose_name_plural': ' Inscusion Out',
            },
        ),
    ]
