# Generated by Django 3.1.1 on 2021-02-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0017_inscusionout'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscusionout',
            name='no_of_doses',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnois'),
        ),
    ]
