# Generated by Django 3.1.1 on 2021-02-20 06:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0018_inscusionout_no_of_doses'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidamount',
            name='partial_paid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Partial Paid'),
        ),
    ]
