# Generated by Django 3.1.1 on 2021-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0019_paidamount_partial_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscusionout',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
    ]
