# Generated by Django 3.1.1 on 2021-02-06 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Id')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile No.')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date')),
                ('flag', models.BooleanField(default=0, verbose_name='Is Login')),
                ('area', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Company_area', to='Configuration.areamaster', verbose_name='Area')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_auth_user', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Company_user_type', to='Configuration.usertype', verbose_name='User Type')),
            ],
            options={
                'verbose_name': 'Super Admin',
                'verbose_name_plural': 'Super Admin',
            },
        ),
    ]
